image: reg.handtruth.com/roots/kotlin/build

stages:
  - build
  - test
  - package

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  GIT_SUBMODULE_STRATEGY: normal

Build:
  stage: build
  script:
    - ./gradlew -Pci --console=plain --no-daemon --max-workers=1 --stacktrace assemble
  artifacts:
    paths:
      - build

Test:
  stage: test
  script:
    - ./gradlew -Pci --console=plain --no-daemon --max-workers=1 --stacktrace check
  artifacts:
    paths:
      - build

.AndroidTest:
  stage: test
  script:
    - adb connect android
    - ./gradlew -Pci --console=plain --no-daemon --max-workers=1 --stacktrace :test-app:connectedAndroidTest
  artifacts:
    paths:
      - build

Package:
  stage: package
  script:
    - ./gradlew -Pci --console=plain --no-daemon --max-workers=1 --stacktrace publishToMavenLocal
  tags: [ package ]
  only:
    - tags
